// @generated by protoc-gen-validate-zod v0.0.1-dev with parameter "target=ts"
// @generated from file tests/harness/cases/yet_another_package/embed.proto (package tests.harness.cases.yet_another_package, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import { z } from "zod";
import { Embed_Enumerated } from "./embed_pb.js";
import { int64, numberGt } from "protobuf-zod";
import { protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum tests.harness.cases.yet_another_package.Embed.Enumerated
 */
export const Embed_EnumeratedSchema = z.nativeEnum(Embed_Enumerated);

/**
 * Validate message embedding across packages.
 *
 * @generated from message tests.harness.cases.yet_another_package.Embed
 */
export const EmbedSchema = z.object({
  /**
   * @generated from field: int64 val = 1;
   * @validate  {"int64":{"gt":"0"}}
   */
  val: int64.refine(numberGt(protoInt64.zero)),
});
