// @generated by protoc-gen-validate-zod v0.0.1-dev with parameter "target=ts"
// @generated from file tests/harness/cases/kitchen_sink.proto (package tests.harness.cases, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import { z } from "zod";
import { ComplexTestEnum } from "./kitchen_sink_pb.js";
import { bytes, bytesEquals, double, float, int32, isIn, map, numberGt, numberLt, oneof, sint32 } from "protobuf-zod";

/**
 * @generated from enum tests.harness.cases.ComplexTestEnum
 */
export const ComplexTestEnumSchema = z.nativeEnum(ComplexTestEnum);

/**
 * @generated from message tests.harness.cases.ComplexTestMsg
 */
export const ComplexTestMsgSchema = z.object({
  /**
   * @generated from field: string const = 1;
   * @validate  {"string":{"const":"abcd"}}
   */
  const: z.string().and(z.literal("abcd")),
  /**
   * @generated from field: tests.harness.cases.ComplexTestMsg nested = 2;
   */
  nested: z.lazy(() => ComplexTestMsgSchema).nullish(),
  /**
   * @generated from field: int32 int_const = 3;
   * @validate  {"int32":{"const":5}}
   */
  intConst: int32.and(z.literal(5)),
  /**
   * @generated from field: bool bool_const = 4;
   * @validate  {"bool":{"const":false}}
   */
  boolConst: z.boolean().and(z.literal(false)),
  /**
   * @generated from field: google.protobuf.FloatValue float_val = 5;
   * @validate  {"float":{"gt":0}}
   */
  floatVal: float.refine(numberGt(0)).nullish(),
  /**
   * @generated from field: google.protobuf.Duration dur_val = 6;
   * @validate  {"duration":{"required":true,"lt":"17s"}}
   */
  durVal: z.any().nullish(),
  /**
   * @generated from field: google.protobuf.Timestamp ts_val = 7;
   * @validate  {"timestamp":{"gt":"1970-01-01T00:00:07Z"}}
   */
  tsVal: z.any().nullish(),
  /**
   * @generated from field: tests.harness.cases.ComplexTestMsg another = 8;
   */
  another: z.lazy(() => ComplexTestMsgSchema).nullish(),
  /**
   * @generated from field: float float_const = 9;
   * @validate  {"float":{"lt":8}}
   */
  floatConst: float.refine(numberLt(8)),
  /**
   * @generated from field: double double_in = 10;
   * @validate  {"double":{"in":[456.789,123]}}
   */
  doubleIn: double.refine(isIn([456.789, 123])),
  /**
   * @generated from field: tests.harness.cases.ComplexTestEnum enum_const = 11;
   * @validate  {"enum":{"const":2}}
   */
  enumConst: z.lazy(() => ComplexTestEnumSchema).and(z.literal(2)),
  /**
   * @generated from field: google.protobuf.Any any_val = 12;
   * @validate  {"any":{"in":["type.googleapis.com/google.protobuf.Duration"]}}
   */
  anyVal: z.any().nullish(),
  /**
   * @generated from field: repeated google.protobuf.Timestamp rep_ts_val = 13;
   * @validate  {"repeated":{"items":{"timestamp":{"gte":"1970-01-01T00:00:00.001Z"}}}}
   */
  repTsVal: z.any().nullish().array(),
  /**
   * @generated from field: map<sint32, string> map_val = 14;
   * @validate  {"map":{"keys":{"sint32":{"lt":0}}}}
   */
  mapVal: map(sint32.refine(numberLt(0)), z.string()),
  /**
   * @generated from field: bytes bytes_val = 15;
   * @validate  {"bytes":{"const":"AJk="}}
   */
  bytesVal: bytes.refine(bytesEquals(new Uint8Array([0x00, 0x99]))),
  /**
   * @generated from oneof tests.harness.cases.ComplexTestMsg.o
   */
  o: oneof([
    z.object({
      /**
       * @generated from field: string x = 16;
       */
      case: z.literal("x"),
      value: z.string(),
    }),
    z.object({
      /**
       * @generated from field: int32 y = 17;
       */
      case: z.literal("y"),
      value: int32,
    }),
  ]),
});

/**
 * @generated from message tests.harness.cases.KitchenSinkMessage
 */
export const KitchenSinkMessageSchema = z.object({
  /**
   * @generated from field: tests.harness.cases.ComplexTestMsg val = 1;
   */
  val: z.lazy(() => ComplexTestMsgSchema).nullish(),
});
