// @generated by protoc-gen-validate-zod v0.0.1-dev with parameter "target=ts"
// @generated from file tests/harness/cases/wkt_nested.proto (package tests.harness.cases, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import { z } from "zod";

/**
 * @generated from message tests.harness.cases.WktLevelOne.WktLevelTwo.WktLevelThree
 */
export const WktLevelOne_WktLevelTwo_WktLevelThreeSchema = z.object({
  /**
   * @generated from field: string uuid = 1;
   * @validate  {"string":{"uuid":true}}
   */
  uuid: z.string(),
});

/**
 * @generated from message tests.harness.cases.WktLevelOne.WktLevelTwo
 */
export const WktLevelOne_WktLevelTwoSchema = z.object({
  /**
   * @generated from field: tests.harness.cases.WktLevelOne.WktLevelTwo.WktLevelThree three = 1;
   * @validate  {"message":{"required":true}}
   */
  three: z.lazy(() => WktLevelOne_WktLevelTwo_WktLevelThreeSchema),
});

/**
 * @generated from message tests.harness.cases.WktLevelOne
 */
export const WktLevelOneSchema = z.object({
  /**
   * @generated from field: tests.harness.cases.WktLevelOne.WktLevelTwo two = 1;
   * @validate  {"message":{"required":true}}
   */
  two: z.lazy(() => WktLevelOne_WktLevelTwoSchema),
});
