// @generated by protoc-gen-validate-zod v0.0.2-dev with parameter "target=ts"
// @generated from file tests/harness/cases/wkt_any.proto (package tests.harness.cases, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {z} from "zod";

/**
 * @generated from message tests.harness.cases.AnyNone
 */
export const AnyNoneSchema = z.object({
  /**
   * @generated from field: google.protobuf.Any val = 1;
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.AnyRequired
 */
export const AnyRequiredSchema = z.object({
  /**
   * @generated from field: google.protobuf.Any val = 1;
   * @validate  {"any":{"required":true}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.AnyIn
 */
export const AnyInSchema = z.object({
  /**
   * @generated from field: google.protobuf.Any val = 1;
   * @validate  {"any":{"in":["type.googleapis.com/google.protobuf.Duration"]}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.AnyNotIn
 */
export const AnyNotInSchema = z.object({
  /**
   * @generated from field: google.protobuf.Any val = 1;
   * @validate  {"any":{"notIn":["type.googleapis.com/google.protobuf.Timestamp"]}}
   */
  val: z.any().nullish(),
});

