// @generated by protoc-gen-validate-zod v0.0.1-dev with parameter "target=ts"
// @generated from file tests/harness/cases/wkt_duration.proto (package tests.harness.cases, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {z} from "zod";
import {int32, numberGt} from "protobuf-zod";

/**
 * @generated from message tests.harness.cases.DurationNone
 */
export const DurationNoneSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationRequired
 */
export const DurationRequiredSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"required":true}}
   */
  val: z.any().nullish(),
});

/**
 * TODO(htuch): Add a very large duration, e.g. {seconds: 315576000000}, once
 * #34 is resolved.
 *
 * @generated from message tests.harness.cases.DurationConst
 */
export const DurationConstSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"const":"3s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationIn
 */
export const DurationInSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"in":["1s","0.000001s"]}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationNotIn
 */
export const DurationNotInSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"notIn":["0s"]}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationLT
 */
export const DurationLTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"lt":"0s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationLTE
 */
export const DurationLTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"lte":"1s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationGT
 */
export const DurationGTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"gt":"0.000001s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationGTE
 */
export const DurationGTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"gte":"0.001s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationGTLT
 */
export const DurationGTLTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"lt":"1s","gt":"0s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationExLTGT
 */
export const DurationExLTGTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"lt":"0s","gt":"1s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationGTELTE
 */
export const DurationGTELTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"lte":"3600s","gte":"60s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.DurationExGTELTE
 */
export const DurationExGTELTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration val = 1;
   * @validate  {"duration":{"lte":"60s","gte":"3600s"}}
   */
  val: z.any().nullish(),
});

/**
 * Regression for earlier bug where missing Duration field would short circuit
 * evaluation in C++.
 *
 * @generated from message tests.harness.cases.DurationFieldWithOtherFields
 */
export const DurationFieldWithOtherFieldsSchema = z.object({
  /**
   * @generated from field: google.protobuf.Duration duration_val = 1;
   * @validate  {"duration":{"lte":"1s"}}
   */
  durationVal: z.any().nullish(),
  /**
   * @generated from field: int32 int_val = 2;
   * @validate  {"int32":{"gt":16}}
   */
  intVal: int32.refine(numberGt(16)),
});

