// @generated by protoc-gen-validate-zod v0.0.2-dev with parameter "target=ts"
// @generated from file tests/harness/cases/wkt_timestamp.proto (package tests.harness.cases, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {z} from "zod";

/**
 * @generated from message tests.harness.cases.TimestampNone
 */
export const TimestampNoneSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampRequired
 */
export const TimestampRequiredSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"required":true}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampConst
 */
export const TimestampConstSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"const":"1970-01-01T00:00:03Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampLT
 */
export const TimestampLTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"lt":"1970-01-01T00:00:00Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampLTE
 */
export const TimestampLTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"lte":"1970-01-01T00:00:01Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampGT
 */
export const TimestampGTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"gt":"1970-01-01T00:00:00.000001Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampGTE
 */
export const TimestampGTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"gte":"1970-01-01T00:00:00.001Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampGTLT
 */
export const TimestampGTLTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"lt":"1970-01-01T00:00:01Z","gt":"1970-01-01T00:00:00Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampExLTGT
 */
export const TimestampExLTGTSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"lt":"1970-01-01T00:00:00Z","gt":"1970-01-01T00:00:01Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampGTELTE
 */
export const TimestampGTELTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"lte":"1970-01-01T01:00:00Z","gte":"1970-01-01T00:01:00Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampExGTELTE
 */
export const TimestampExGTELTESchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"lte":"1970-01-01T00:01:00Z","gte":"1970-01-01T01:00:00Z"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampLTNow
 */
export const TimestampLTNowSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"ltNow":true}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampGTNow
 */
export const TimestampGTNowSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"gtNow":true}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampWithin
 */
export const TimestampWithinSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"within":"3600s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampLTNowWithin
 */
export const TimestampLTNowWithinSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"ltNow":true,"within":"3600s"}}
   */
  val: z.any().nullish(),
});

/**
 * @generated from message tests.harness.cases.TimestampGTNowWithin
 */
export const TimestampGTNowWithinSchema = z.object({
  /**
   * @generated from field: google.protobuf.Timestamp val = 1;
   * @validate  {"timestamp":{"gtNow":true,"within":"3600s"}}
   */
  val: z.any().nullish(),
});

