// @generated by protoc-gen-es v0.2.1 with parameter "target=ts"
// @generated from file tests/harness/cases/other_package/embed.proto (package tests.harness.cases.other_package, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * Validate message embedding across packages.
 *
 * @generated from message tests.harness.cases.other_package.Embed
 */
export class Embed extends Message<Embed> {
  /**
   * @generated from field: int64 val = 1;
   */
  val = protoInt64.zero;

  constructor(data?: PartialMessage<Embed>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "tests.harness.cases.other_package.Embed";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "val", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Embed {
    return new Embed().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Embed {
    return new Embed().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Embed {
    return new Embed().fromJsonString(jsonString, options);
  }

  static equals(a: Embed | PlainMessage<Embed> | undefined, b: Embed | PlainMessage<Embed> | undefined): boolean {
    return proto3.util.equals(Embed, a, b);
  }
}

/**
 * @generated from enum tests.harness.cases.other_package.Embed.Enumerated
 */
export enum Embed_Enumerated {
  /**
   * @generated from enum value: VALUE = 0;
   */
  VALUE = 0,
}
// Retrieve enum metadata with: proto3.getEnumType(Embed_Enumerated)
proto3.util.setEnumType(Embed_Enumerated, "tests.harness.cases.other_package.Embed.Enumerated", [
  { no: 0, name: "VALUE" },
]);

/**
 * @generated from message tests.harness.cases.other_package.Embed.DoubleEmbed
 */
export class Embed_DoubleEmbed extends Message<Embed_DoubleEmbed> {
  constructor(data?: PartialMessage<Embed_DoubleEmbed>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "tests.harness.cases.other_package.Embed.DoubleEmbed";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Embed_DoubleEmbed {
    return new Embed_DoubleEmbed().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Embed_DoubleEmbed {
    return new Embed_DoubleEmbed().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Embed_DoubleEmbed {
    return new Embed_DoubleEmbed().fromJsonString(jsonString, options);
  }

  static equals(
    a: Embed_DoubleEmbed | PlainMessage<Embed_DoubleEmbed> | undefined,
    b: Embed_DoubleEmbed | PlainMessage<Embed_DoubleEmbed> | undefined
  ): boolean {
    return proto3.util.equals(Embed_DoubleEmbed, a, b);
  }
}

/**
 * @generated from enum tests.harness.cases.other_package.Embed.DoubleEmbed.DoubleEnumerated
 */
export enum Embed_DoubleEmbed_DoubleEnumerated {
  /**
   * @generated from enum value: VALUE = 0;
   */
  VALUE = 0,
}
// Retrieve enum metadata with: proto3.getEnumType(Embed_DoubleEmbed_DoubleEnumerated)
proto3.util.setEnumType(
  Embed_DoubleEmbed_DoubleEnumerated,
  "tests.harness.cases.other_package.Embed.DoubleEmbed.DoubleEnumerated",
  [{ no: 0, name: "VALUE" }]
);
