name: CI
on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    timeout-minutes: 20

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.14.1

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - uses: actions/cache@v3
        name: Set up turborepo cache
        with:
          path: .turbocache
          key: ${{ runner.os }}-turbocache-verify-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbocache-verify-
            ${{ runner.os }}-turbocache-

      - name: Lint
        run: pnpm turbo run lint --cache-dir .turbocache

      - name: Typecheck
        run: pnpm turbo run typecheck --cache-dir .turbocache

      - name: Test
        run: pnpm turbo run test --cache-dir .turbocache
